// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAurGIWtNJEHo9-ChP2vYKHFspSPOgRVYc',
    appId: '1:828770828147:web:0aab67d6731e39c0cf0f06',
    messagingSenderId: '828770828147',
    projectId: 'mobile-banking-app-26a13',
    authDomain: 'mobile-banking-app-26a13.firebaseapp.com',
    storageBucket: 'mobile-banking-app-26a13.firebasestorage.app',
    measurementId: 'G-W3JWEB7XNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qTBnlVviq80fYMoS3lsJ0y0JYtYAyv0',
    appId: '1:828770828147:android:cad8ad9e5aacf0e9cf0f06',
    messagingSenderId: '828770828147',
    projectId: 'mobile-banking-app-26a13',
    storageBucket: 'mobile-banking-app-26a13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA3HOAN1WQaKQKe7n0f5q3i7ldMZDFnP4',
    appId: '1:828770828147:ios:140126c1239395c4cf0f06',
    messagingSenderId: '828770828147',
    projectId: 'mobile-banking-app-26a13',
    storageBucket: 'mobile-banking-app-26a13.firebasestorage.app',
    iosBundleId: 'com.example.mobileBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA3HOAN1WQaKQKe7n0f5q3i7ldMZDFnP4',
    appId: '1:828770828147:ios:140126c1239395c4cf0f06',
    messagingSenderId: '828770828147',
    projectId: 'mobile-banking-app-26a13',
    storageBucket: 'mobile-banking-app-26a13.firebasestorage.app',
    iosBundleId: 'com.example.mobileBankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAurGIWtNJEHo9-ChP2vYKHFspSPOgRVYc',
    appId: '1:828770828147:web:51750ae8fc4fcc06cf0f06',
    messagingSenderId: '828770828147',
    projectId: 'mobile-banking-app-26a13',
    authDomain: 'mobile-banking-app-26a13.firebaseapp.com',
    storageBucket: 'mobile-banking-app-26a13.firebasestorage.app',
    measurementId: 'G-P8ML5PT34X',
  );
}
